### ISSUE TITLE
Needed instructions on how to build (Linux, Windows and macOS)

### ISSUE THREAD

**Issue by gerrydoro** [performous/performous-tools#3]
Hi,
is there a way someone can add a `readme.md` with instructions on how to build the tools from source?
The `performous-tools` package for Ubuntu seems not working anymore.
Building on macOS generated just some of the tools but not all of them (I especially need the `ss_extract` one).
Many thanks

**Comment by Tronic** [comment]
The instructions for building (the game incl. tools) from source are in
https://github.com/performous/performous/wiki/Building-and-installing-from-source
